name: dawnsiven's Blog
url: 
description: place my thoughts and share my experience.

permalink: /themes/:title/

plugins: [jekyll-paginate]

highlighter: pygments
paginate: 20

markdown: rdiscount
rdiscount:
    extensions: ['smart']

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile', 'vendor']
