title: dawnsiven's Blog
author: dawnsiven
url: https://dawnsiven.github.io
description: Notes, projects, problems, and small ideas.

theme: no-style-please
markdown: kramdown

theme_config:
  back_home_text: home
  date_format: "%Y-%m-%d"
  show_description: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - README.md
  - Gemfile.lock
  - Gemfile
  - Rakefile
  - vendor
